### PR TITLE
Initial commit of SPM FORMULA

### PR DESCRIPTION
**Pull request by techhat**

### CODE REVIEW

**Comment by techhat** [comment]
http://docs.saltstack.com/en/develop/topics/spm/

**Comment by iggy** [comment]
Shouldn't that be FORMULA.yml (and odd that .yml was chosen over .yaml... also odd that this is the first anyone has seemingly heard of any of this...)

**Comment by techhat** [comment]
We decided against using the .yml extension.

**Comment by iggy** [comment]
The documentation you linked says FORMULA.yml all over it, so I'm sure you can see where the confusion comes from.

**Comment by techhat** [comment]
My bad, thanks for pointing that out @iggy. I'll get it cleaned up.

**Comment by techhat** [comment]
saltstack/salt#25208

**Comment by iggy** [comment]
Is there a general place we can discusss/give feedback about this SPM idea or just in the main salt issue tracker?

**Comment by puneetk** [comment]
Also please add some sort of note to the Readme that this is now available as a feature please.

**Comment by techhat** [comment]
The initial PR was saltstack/salt#24896. There have been several since. Since it is a feature of mainline Salt, issues with the program itself should go in Salt's issue tracker.

**Comment by techhat** [comment]
PRs can be found at https://github.com/saltstack/salt/pulls?utf8=%E2%9C%93&q=is%3Apr+spm+

**Comment by puneetk** [comment]
No issues with the program, just need it documented it in the formula itself that the formula spm package won’t work in salt versions lesser than <insert version here>

**Comment by techhat** [comment]
@puneetk, makes sense. Since 2015.8 is the first version of Salt to have SPM, that is considered the first version that any FORMULA file will work with. The `spm` command itself doesn't enforce that yet, but it's on my list for this week.

**Comment by puneetk** [comment]
thank you :)

**Pull request merged**
