### PR TITLE
Switch Debian apt repo to https

### PR DESCRIPTION
**Pull request by xenadmin**
The title says it all. 

Maybe a Requirement has do be added there?

    - require:
      - pkg: apt-transport-https

### CODE REVIEW

**Comment by aboe76** [comment]
@xenadmin that won't work without the resource:
```
apt-transport-https:
  pkg.installed:
    - name:  apt-transport-https
```

**Comment by xenadmin** [comment]
I'm not familiar with the standards here, would that be something being considered, if I add a `pkg.installed` into the `repo.sls` ? If yes, I can alter the pull request.

**Comment by aboe76** [comment]
@xenadmin you can add it in the repo.sls because this package is only used with apt.
Just add it before the ```{{ id_prefix }}_repo:``` in between the if statement os of_family ' Debian'

**Comment by xenadmin** [comment]
I added the apt-transport-https as you suggested.

**Comment by aboe76** [comment]
@xenadmin nice, merged it.

**Pull request merged**
