### PR TITLE
refactor(map and defaults): Update the map.jinja file and add yaml maps

### PR DESCRIPTION
**Pull request by absmith82**
This changes the map.jinja file to be more like the standard template.  It also adds defaults, osfamlymap, osfingermap, and osmap yaml files for easy mapping of the proper packages and settings for each OS and version of the OS.

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@absmith82 Thanks for starting this, it's a very useful PR. An initial comment: all of these files need to be moved to the `zabbix` directory, including replacing the current `map.jinja`. Also, this repo now uses `semantic-release`, so the commit messages need to be formatted accordingly. Please see the link to that from the `README`.

**Comment by absmith82** [comment]
You are right,

Sorry I was careless and just uploaded the files to the wrong place after testing on my test server.  I'll check the readme and reformat the commit message and fix the file structure.

Thanks

**Comment by myii** [comment]
@absmith82 I've run some tests to compare the map that is produced before and after this PR.  The results need to be identical for a successful conversion.  I've been able to fix things at my end, so I'll append a commit to this PR in a little while, so that you can look over the changes made.  Once we're happy with that, we can squash the whole PR to fix the commit message, so that we get `semantic-release` working -- changing the title of the PR isn't enough, unfortunately.

**Comment by absmith82** [comment]
Thanks for the update. I've been looking at the Travis ci tests and it
looks like the tests are failing because of repo issues.  But any updates
to make it the same as before would be fine with me.  I literally just the
old map.jinja values and translated then into the different yaml map files
I may have changed the postgres packages due to the old ones being virtual
packages.

**Comment by myii** [comment]
> Thanks for the update. I've been looking at the Travis ci tests and it looks like the tests are failing because of repo issues. But any updates to make it the same as before would be fine with me. I literally just the old map.jinja values and translated then into the different yaml map files I may have changed the postgres packages due to the old ones being virtual packages.

#### Issues

@absmith82 It's easiest to cover the situation by looking at the diffs.  For all of the diffs, due to the nature of how I was generating the changes, anything with a minus (`-`) at the beginning is something which isn't quite right.  It needs to be changed back to the corresponding line(s) with a plus (`+`), or shouldn't be there at all:

* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287058#L1594 -- `debian-10`
  - Mainly minor formatting issues
  - Pillar not being merged properly
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287059#L1613 -- `ubuntu-1804`
  - Mostly the same as `debian-10` but also the PostgreSQL changes you mentioned
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287060#L1578 -- `centos-8`
  - Some issues with lists not having a space between the dash and the data
  - Same as `debian-10` otherwise
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287061#L1602 -- `fedora-31`
  - Same issues as `centos-8` (RedHat)
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287062#L1549 -- `opensuse-leap-151`
  - Same issues as `debian-10`
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287063#L1813 -- `amazonlinux-2`
  - Same issues as `centos-8` (RedHat)
* https://travis-ci.org/github/myii/zabbix-formula/jobs/665287064#L3218 -- `arch-base-latest`
  - Same issues as `debian-10`

#### Resolution

See https://github.com/saltstack-formulas/zabbix-formula/compare/3d324d9...b7c0977 for the changes that have been added to this PR.

1. Fixed `map.jinja`:
  - Only the pillar `lookup` should be merged, not the whole pillar
  - Used the latest structure from the `template-formula`
2. Fixed `osfamilymap.yaml`:
  - Added a space after the dash in each list entry
  - Resolved minor formatting
3. Modified `osmap.yaml`:
  - Used the latest structure from the `template-formula`
4. Fixed `osfingermap.yaml`:
  - Removed the PostgreSQL entries for Ubuntu 18.04 and 16.04 -- these can be tackled in a subsequent PR, this PR should be a pure refactor only
  - Used the latest structure from the `template-formula`

#### Result

All of the platforms are now passing:

* https://travis-ci.org/github/myii/zabbix-formula/builds/665299638

#### Remaining steps

After confirming the changes, the commits need to be fixed so that `semantic-release` runs properly.  The easiest way to do that is squashing the commits when merging this PR.

**Comment by myii** [comment]
@absmith82 So just to confirm, all of the platforms are passing for this PR:

* https://travis-ci.com/github/saltstack-formulas/zabbix-formula/builds/154412355

The only thing remaining is the `commitlint`, so if you're OK with the changes that I've added, I'll squash and merge this PR, fixing the commit message at the same time.

**Comment by absmith82** [comment]
I have no problems with the changes you made. Most were formatting mistakes I made so if you can squash the commit to fix the commitlint test that would be great.

**Comment by myii** [comment]
Thanks @absmith82, merged and released successfully:

* https://github.com/saltstack-formulas/zabbix-formula/releases/tag/v0.21.3

**Comment by myii** [comment]
@absmith82 One more thing, you may want to send through a PR regarding the `osfinger` changes for Ubuntu 18.04 and 16.04.  That can now be considered for inclusion as a new feature.

**Comment by myii** [comment]
@absmith82 Just got reminded that #123 already contains the suggestion for updating all of the platforms to `3.0`, so it might be worth working with that in mind for any new PR.

**Pull request merged**
