### PR TITLE
added default values back in to prevent conflicts as requested

### PR DESCRIPTION
**Pull request by ericsysmin**

### CODE REVIEW

**Comment by michaelforge** [comment]
Wow... Looks like a lot of work, but..
What I meant in #21 is adding appeared pillar options to `pillar.example`, not adding fallbacks right into templates. Sorry for this miscommunication made by me.
Zabbix itself already has defaults that works even if options is not mentioned in config at all. It could be hard to keep them synced with templates in future.

I'm not the master of this repo, but after reconsidering all this + #21 , sharing my view:
`pillar.example` (at least agent) could contain only options that's needed to connect to Zabbix Server + OS related/best practice values forced in default configs of official distro-packages, e.g.: ea35c642d6
For anything else, existing `extra_conf:` probably would be enough.

Share your thoughts please. =)
Maybe you see better scenario (e.g. for your needs)?

**Comment by mchugh19** [comment]
I think this pull request is important in that it cleans up the defaults for necessary config file options. Take pidfile for example, without this patch, every environment is forced to declare a pidfile in a pillar. However, the pidfile is really controlled by the systemd service file, so it really makes no sense to adjust it, a sane default should be used. The current non standard `{% if settings.get` syntax should really be simplified to the `{{ settings.get(whatever, default)` version.

**Comment by ericsysmin** [comment]
I can make these changes if you'd like.

**Comment by hatifnatt** [comment]
Any reason why this is not merged?
I think best approach is reference to Zabbix configuration file where some parameters are defined explicitly even most of them have some default value. _LogFileSize_ fo example. Those defaults can be added to map.jinja and used to generate config almost same as in packages. There is not many of those parameters and most of them already in map.jinja . With this approach in pillar users only need to specify parameters they want to change from defaults.
I already do some work in this direction https://github.com/saltstack-formulas/zabbix-formula/compare/master...hatifnatt:dev if it's look fine I will create PR. And continue with proxy and server config.

**Comment by pauldalewilliams** [comment]
Given the changes in #71 and #82, is this PR necessary any longer?  Seems like agent and server have already been covered by @hatifnatt and sounds like changes to the proxy conf are forthcoming and will follow a similar structure to what has already been merged.

**Pull request closed without merging**
