### PR TITLE
Updated to support all versions of zabbix-agent config

### PR DESCRIPTION
**Pull request by ericsysmin**

### CODE REVIEW

**Comment by michaelforge** [comment]
@ericsysmin 
Woah, thanks for comparison work! :open_mouth: 
Much more settings now available to be configured through Salt.

This commit erasing default `LogFileSize` value from zabbix_agentd.conf, which historically was 0 (at least in deb-packages). 
I'll try to put it back in default pillar with next commit.

**Comment by ericsysmin** [comment]
{% if settings.get('logfilesize', false) %}LogFileSize={{ settings.get('logfilesize') }}{% endif %}

its there if it's defined on line 83 @michaelforge

**Comment by ericsysmin** [comment]
Ohhh, i see what you're saying, but by default, i believe zabbix assumes 1 so it's not a mandatory value @michaelforge

**Comment by ericsysmin** [comment]
`
### Option: LogFileSize
#	Maximum size of log file in MB.
#	0 - disable automatic log rotation.
#
# Mandatory: no
# Range: 0-1024
# Default:
# LogFileSize=1`

**Comment by michaelforge** [comment]
@ericsysmin 
Right-right, but before this PR this option was hardcoded as '0':
https://github.com/saltstack-formulas/zabbix-formula/blob/f64d6a561b2f8d172304e1f4c10ffbae9b7ce142/zabbix/files/default/etc/zabbix/zabbix_agentd.conf.jinja#L8

The same behavior exists in default debian config - it's 0 by default.
But Zabbix Agent's own default is 1.

At the moment, there is no default pillar option "logfilesize".
That means that this PR would reset `LogFileSize` for everyone to '1'.

I'll commit default pillar in a moment :+1:

**Comment by ericsysmin** [comment]
ah got it, understood, i can add in more default pillars too if you would like, some operating systems have some differences, my goal is to actually open this one up so that we can use it on Ubuntu, Debian, CentOS distributions, and support all versions of Zabbix including 3.0

**Comment by michaelforge** [comment]
@ericsysmin 
Overall it's a good idea, especially for such possible differs between distros.
On the other hand, adding **all** options would make `pillar.example` look over bloated and harder to read, while most of those options are not mandatory and being used only at specific situations.

Anyway, those options are already templated now, so it would be better to add them to pillar. Thanks in advance!

**Comment by ericsysmin** [comment]
@michaelforge so for defaults, do you want me to leave them in the template? or do we want to be able to put them in zabbix/map.jinja, its up to you, also, non of these are mandatory, so someone doesn't need a big pillar, it's basically modeled exactly after ansible-zabbix-agent and puppet-zabbix templates,

**Comment by ericsysmin** [comment]
or i can add some of them to pillar.example

**Comment by michaelforge** [comment]
@ericsysmin 
You mean #24 ? Or current PR?

**Comment by hatifnatt** [comment]
I have a question why
```
# Mandatory:
# Range:
# Default:
```
have been removed from most places except TLS part?

**Pull request merged**
