### PR TITLE
Update zabbix_proxy.conf.jinja

### PR DESCRIPTION
**Pull request by unsupo**
This will allow the same format for all the other conf files
zabbix:
\tlookup:
\t\tproxy:
\t\t\tsourceip: ....

### CODE REVIEW

**Comment by xenadmin** [comment]
This looks really good, is there a reason this wasn't merged?

**Comment by unsupo** [comment]
@xenadmin I need someone with write access to this repository to merge this pull request

**Comment by aboe76** [comment]
@xenadmin if I merge this first, you might need to rebase #105

**Comment by xenadmin** [comment]
I you tell me how I update my fork, after the merge of #96 I will gladly adjust my pull request and offer it again. :-)

**Comment by aboe76** [comment]
@xenadmin please read this :
https://help.github.com/articles/syncing-a-fork/

**Pull request merged**
