### PR TITLE
New gpg key

### PR DESCRIPTION
**Pull request by t0fik**
Added support for new gpg keys for RedHat.
Fixed reading osmajorrelease grain.

### CODE REVIEW

**Comment by t0fik** [comment]
Branch is 5 commits ahead master.

**Comment by pauldalewilliams** [comment]
@t0fik I should clarify - the commit is missing several changes that have been merged since Jan 20 when your commits were made.  If you take a look at the changed files you'll see your PR will undo a lot of those changes if merged as is.

**Comment by t0fik** [comment]
OK. I'll merge my change and create new PR

**Comment by pauldalewilliams** [comment]
Sounds good.  Thank you!

**Pull request closed without merging**
