### PR TITLE
Fix dbpassword references

### PR DESCRIPTION
**Pull request by pauldalewilliams**
With the recent commits (PR #82) to update the Zabbix server conf files a reference to dbpassword was introduced.  This is inconsistent with pillar.example and usage in other states, which references dbpass.  Without these changes, the conf files will end up with the wrong password for people who are following pillar.example.

### CODE REVIEW

**Comment by pauldalewilliams** [comment]
That would make sense but could be a breaking change for people who followed the original structure and examples.  Do you think it's worth changing the variable name in that case?  My feeling is we should make the template conform with the original choice, even though `dbpassword` would have been a better choice.

**Comment by hatifnatt** [comment]
@pauldalewilliams I'm currently working on zabbix.mysql.* states which are using `dbpass` if you can wait, I will present relatively big PR where `dbpass` will be updated to `dbpassword` everywhere with backward compatibility + other improvements.
I'm Ok with rollback to `dbpass` instead of `dbpassword` but I think it will be useful to hear the 3-rd person opinion.
@landergate you thoughts about the topic?

**Comment by pauldalewilliams** [comment]
@hatifnatt Hmmm, ok.  I'll hold off on a PR I was going to do then for the mysql states.  I wanted to do some tweaks to allow for the sql scripts needed for 3.4 to be included.  I'll see what you come up with and maybe we can combine them.  I've tested mine and they're working, but sounds like you've got some bigger things in mind.

**Comment by hatifnatt** [comment]
@pauldalewilliams maybe you can publish what you have in your fork in separate branch? So I can take a look and we don't work on same thing.

**Comment by pauldalewilliams** [comment]
I'll try to do that tonight.  I've tested it and it works well.  However, it still uses `dbpass`.

**Comment by landergate** [comment]
@pauldalewilliams 
Could you check please if things are working as expected after c3c2f8c3?

**Comment by hatifnatt** [comment]
@pauldalewilliams  can you give some feedback or can this be closed? PR #86 merged to formula more than a year ago, and I think now it can be considered as "time proven solution" :)

**Comment by hatifnatt** [comment]
After #86 #118 and #143 `dbpass` not present in this formula anymore (except the compatibility part). I consider original issue is solved.

**Pull request closed without merging**
