### PR TITLE
fix(fedora): get all `fedora` instances working (`2018.3`+)

### PR DESCRIPTION
**Pull request by myii**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes:

```
BREAKING CHANGE: Minimum Salt version support is now `2018.3` in line
with official upstream support; also use of the `traverse` Jinja filter.
```

### Related issues and/or pull requests

* Semi-automated using https://github.com/myii/ssf-formula/pull/143

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
CC: @hatifnatt @xenadmin @absmith82 @OrangeDog -- I'm pinging you all since you use/develop this formula.

This PR involves a `BREAKING CHANGE` as mentioned above.  The minimum supported version of Salt will be `2018.3` once this is merged, which we're beginning to roll out across all repos (see https://www.saltstack.com/product-support-lifecycle/).  I'll leave this for a couple of days, to allow time for any objections to this.

**Comment by absmith82** [comment]
would you need to change the user information in zabbix/users.sls as well to match your new user scheme?

**Comment by myii** [comment]
@absmith82 Excellent catch, I forgot to mention that.  Fedora prepares a `zabbixsrv` account alongside the `zabbix` account.  The former must be used when dealing with the directories or files relevant to the server.  I did start to make a change to the `users.sls` but I wanted to get some opinions about this, since it's only relevant to Fedora, AFAIK.  Since it's already created automatically, I thought I'd leave it out until there's some clarity about it.

**Comment by myii** [comment]
Merged, since no objections raised.  Feel free to comment is there is a problem and we can look at ways to address it.

**Pull request merged**
