### PR TITLE
Fixed osmajorrelease type and new repo keys

### PR DESCRIPTION
**Pull request by t0fik**
- Compability with osmajorrelease being int value
- Added new zabbix 3.2+ repo keys for RedHat

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
@t0fik could you squash your commits before we merge?

**Comment by t0fik** [comment]
@noelmcloughlin Squashed

**Comment by aboe76** [comment]
@t0fik and @noelmcloughlin thanks I have merged it.

**Comment by noelmcloughlin** [comment]
Thanks @t0fik.

**Pull request merged**
